name: Python Linting

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        
    - name: Run linter
      run: |
        # For now, we're allowing the workflow to pass even with linting errors
        # Later we can make this strict by removing the || true
        ruff check . || true
        
    - name: Check fixable linting issues
      run: |
        # This is a helpful step to show what can be fixed automatically
        ruff check --diff .