name: Python Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f pyproject.toml ]; then
          pip install .
          pip install pytest pytest-cov
        else
          pip install pytest pytest-cov
        fi
        
    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term-missing tests/
        
    - name: Check coverage threshold
      run: |
        COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(root.attrib['line-rate'])")
        COVERAGE_PERCENT=$(echo "$COVERAGE * 100" | bc)
        echo "Coverage: ${COVERAGE_PERCENT}%"
        if (( $(echo "$COVERAGE_PERCENT < 85" | bc -l) )); then
          echo "Test coverage is below 85%"
          exit 1
        fi