PERSONA_CREATION_QUESTIONS = [
    {
        "id": "user_email",
        "type": "text",
        "question": "What is your email?",
        "placeholder": "Enter your email",
        "required": True,
        "description": "User email",
    },
    {
        "id": "posting_frequency",
        "type": "text",
        "question": "How often do you post on social media platforms (e.g., Instagram, X/Twitter, LinkedIn, etc.) and what kind of content do you typically share?",
        "placeholder": "Describe your posting frequency and content type",
        "required": True,
        "description": "Trait: Extraversion",
    },
    {
        "id": "posting_style",
        "type": "text",
        "question": "When you post something online, do you usually plan it out or is it spontaneous? Why?",
        "placeholder": "Explain your posting style",
        "required": True,
        "description": "Trait: Conscientiousness",
    },
    {
        "id": "engagement_importance",
        "type": "text",
        "question": "How important are likes, comments, or shares to you when you post something?",
        "placeholder": "Describe your reaction to social engagement",
        "required": True,
        "description": "Trait: Validation",
    },
    {
        "id": "aesthetic_strategy",
        "type": "text",
        "question": "Do you follow a specific aesthetic, theme, or strategy for your online presence? If yes, what motivates it?",
        "placeholder": "Describe your strategy or theme",
        "required": True,
        "description": "Trait: Curation",
    },
    {
        "id": "platform_authenticity",
        "type": "text",
        "question": "Which platform do you feel most yourself on and why?",
        "placeholder": "Mention your preferred platform and why",
        "required": True,
        "description": "Trait: Authenticity",
    },
    {
        "id": "criticism_response",
        "type": "text",
        "question": "How do you typically respond to criticism or negative comments online?",
        "placeholder": "Describe your response style",
        "required": True,
        "description": "Trait: Stability",
    },
    {
        "id": "content_intent",
        "type": "text",
        "question": "Do you consciously aim to influence others or inspire them with your posts, or is your content more personal in nature?",
        "placeholder": "Explain your intent behind content",
        "required": True,
        "description": "Trait: Intentionality",
    },
    {
        "id": "linkedin_url",
        "type": "text",
        "question": "What is your LinkedIn profile URL?",
        "placeholder": "Enter your LinkedIn URL",
        "required": True,
        "description": "LinkedIn URL",
    },
]
