PERSONA_CREATION_QUESTIONS = [
    {
        "id": "user_email",
        "type": "text",
        "question": "What is your email?",
        "placeholder": "Enter your email",
        "required": True,
        "description": "User email",
    },
    {
        "id": "current_role",
        "type": "text",
        "question": "What is your current role?",
        "placeholder": "Enter your current role",
        "required": True,
        "description": "Current role",
    },
    {
        "id": "company_name",
        "type": "text",
        "question": "What is the name of your company?",
        "placeholder": "Enter your company name",
        "required": True,
        "description": "Company name",
    },
    {
        "id": "years_of_experience",
        "type": "number",
        "question": "How many years of experience do you have?",
        "placeholder": "Enter your years of experience",
        "required": True,
        "description": "Years of experience",
    },
    {
        "id": "platform_authenticity",
        "type": "text",
        "question": "Which platform do you feel most yourself on and why?",
        "placeholder": "Mention your preferred platform and why",
        "required": True,
        "description": "Trait: Authenticity",
    },
    {
        "id": "content_intent",
        "type": "text",
        "question": "Do you aim to influence others or is your content more personal?",
        "placeholder": "Explain your intent behind content",
        "required": True,
        "description": "Trait: Intentionality",
    },
    {
        "id": "blog_url",
        "type": "text",
        "question": "What is the URL of your blog?",
        "placeholder": "Enter your blog URL",
        "required": True,
        "description": "Blog URL",
    },
    {
        "id": "social_media_platforms",
        "type": "text",
        "question": "What social media platforms do you use?",
        "placeholder": "Enter your social media platforms",
        "required": True,
        "description": "Social media platforms",
    },
]

extra_questions = [
    {
        "id": "posting_style",
        "type": "text",
        "question": "Do you plan your posts or are they spontaneous? Why?",
        "placeholder": "Explain your posting style",
        "required": True,
        "description": "Trait: Conscientiousness",
    },
    {
        "id": "engagement_importance",
        "type": "text",
        "question": "How important are likes, comments, or shares to you?",
        "placeholder": "Describe your reaction to social engagement",
        "required": True,
        "description": "Trait: Validation",
    },
    {
        "id": "aesthetic_strategy",
        "type": "text",
        "question": "Do you follow a specific aesthetic or theme? What motivates it?",
        "placeholder": "Describe your strategy or theme",
        "required": True,
        "description": "Trait: Curation",
    },
    {
        "id": "posting_frequency",
        "type": "text",
        "question": "How often do you post and what content do you typically share?",
        "placeholder": "Describe your posting frequency and content type",
        "required": True,
        "description": "Trait: Extraversion",
    },
]
